In [1]:
pip install numpy

Defaulting to user installation because normal site-packages is not writeable
Note: you may need to restart the kernel to use updated packages.


In [2]:
import numpy as np

In [13]:
my_list=[10,20,30]
arr1=np.array(my_list)

In [7]:
lists=[[1,2,3],[2,3,4],[5,6,7]]
arr=np.array(lists)

In [5]:
type(np.array(lists))

numpy.ndarray

In [9]:
arr.shape

(3, 3)

In [10]:
arr.dtype

dtype('int32')

In [11]:
arr.reshape

<function ndarray.reshape>

In [12]:
arr.shape

(3, 3)

In [14]:
arr1.reshape

<function ndarray.reshape>

In [15]:
arr1.shape

(3,)

In [16]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [17]:
np.arange(0,10,3)

array([0, 3, 6, 9])

In [19]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [23]:
np.ones((1,2))

array([[1., 1.]])

In [24]:
np.random.rand(2,3)

array([[0.00907672, 0.38617536, 0.71547623],
       [0.02037339, 0.08340636, 0.87958821]])

In [25]:
np.random.randn(2,4)

array([[-0.1577639 , -0.91151361, -1.25592556,  0.56655977],
       [ 1.79630539, -0.78201434,  0.50004878,  1.19597403]])

In [26]:
np.random.randint(10,size=(2,3))

array([[1, 2, 0],
       [4, 9, 5]])